name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}/.output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: Test functions
        run: dotnet test --configuration Release src/Hashflags.Tests

      - name: Publish functions
        run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }} src/Hashflags

      - name: Package functions
        uses: actions/upload-artifact@v3
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      FUNC_APP_NAME: hashflags
    steps:
      - name: Download website
        uses: actions/download-artifact@v3
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNC_APP_NAME }}
          package: ${{ env.OUTPUT_PATH }}
