name: Build and Deploy
env:
  OUTPUT_PATH: ${{ github.workspace }}/.output

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
        
      - name: Test functions
        run: dotnet test --configuration Release src/Hashflags.Tests

      - name: Publish functions
        run: dotnet publish --configuration Release --output ${{ env.OUTPUT_PATH }} src/Hashflags

      - name: Package functions
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    env:
      FUNC_APP_NAME: hashflags
    steps:
      - name: Download website
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: functions
          path: ${{ env.OUTPUT_PATH }}

      - name: 'Login via Azure CLI'
        uses: azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16 # tag=v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@a5745d20de8e03c1d0a2a44a79a670d22989e04f # tag=v1
        with:
          app-name: ${{ env.FUNC_APP_NAME }}
          package: ${{ env.OUTPUT_PATH }}
